add_newline = false

# Sets the prompt symbol
[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

# Show more than the default 3 folders
[directory]
truncation_length = 6
truncate_to_repo = true
truncation_symbol = ".. "
# fish_style_pwd_dir_length = 1

[git_status]
# Replace $allstatus which is short for "$conflicted$stashed$deleted$renamed$modified$staged$untracked"
# to remove $untracked
format = '([\[$conflicted$stashed$deleted$renamed$modified$staged$ahead_behind\]]($style) )'

# Is this broken on PowerShell?
[status]
disabled = false
map_symbol = true

############
# Change bunch of the symbols to Nerd Font symbols
# (From https://starship.rs/presets/#nerd-font-symbols)
# Obviously requires Nerd Font support
############
[aws]
symbol = " "
[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
[cmake]
symbol = "CMake 喝 "
[conda]
symbol = "Conda  "
[dart]
symbol = "Dart  "
[docker]
symbol = "Docker  "
[elixir]
symbol = "Elixir  "
[elm]
symbol = "Elm  "
[git_branch]
symbol = "Git  "
[golang]
symbol = "Go  "
[haskell]
symbol = "Haskell  "
[hg_branch]
symbol = "Hg  "
[java]
symbol = "Java  "
[julia]
symbol = "Julia  "
[memory_usage]
# Has default threshold of 75% even if enabled
disabled = false
format = "Mem $symbol [${ram}]($style) "
symbol = " "
[nim]
symbol = "Nim  "
[nix_shell]
symbol = "Nix  "
[nodejs]
symbol = "NodeJS  "
[package]
symbol = "Package  "
[php]
symbol = "PHP  "
[python]
symbol = "Python  "
[ruby]
symbol = "Ruby  "
[rust]
symbol = "Rust  "
